---
- name: acmetool repository
  apt_repository:
    repo: 'ppa:hlandau/rhea'

- name: install proxy packages
  apt: name={{item}} state=latest update_cache=true
  with_items:
    - varnish
    - hitch
    - acmetool

- name: upload varnish configuration for acmetool
  template:
    src: default.j2
    dest: /etc/varnish/http2_quickly.vcl
    mode: 0644

- name: upload varnish configuration
  template:
    src: minimal.j2
    dest: /etc/varnish/default.vcl
    mode: 0644

- name: reconfigure varnish systemd
  template:
    src: varnish-service.j2
    dest: /etc/systemd/system/varnish.service
    mode: 0755

- name: make sure reconfigure takes
  command: systemctl daemon-reload

- name: restart varnish
  service:
    name: varnish
    state: restarted

- name: upload hitch configuration
  template:
    src: hitch.j2
    dest: /etc/hitch/hitch.conf
    mode: 0644

- name: mk hitch run directory
  file:
    path: /var/lib/hitch
    state: directory
    mode: 0755
    owner: "_hitch"

- name: mk acme conf dir
  file:
    path: /var/lib/acme/conf
    state: directory

- name: configure acmetool
  template:
    src: response-file.j2
    dest: /var/lib/acme/conf/responses
    mode: 0644

- name: issue certs
  shell: acmetool --batch want {{ http2_quickly_hostnames|join(' ') }}

- name: create pem file
  shell: cd /var/lib/acme/live/{{ item }} && cat cert fullchain privkey > haproxy
  with_items: "{{ http2_quickly_hostnames }}"

- name: set permissions
  file:
    path: /var/lib/acme/live/{{ item }}/haproxy
    mode: 0700
  with_items: "{{ http2_quickly_hostnames }}"


- name: restart hitch
  service:
    name: hitch
    state: restarted
